name: DevOps for ML (CI)

on:
  push:
    branches:
    - master
    paths:
    - 'code/*'

jobs:
  training:
    name: Model Training
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r 'aml_service/requirements.txt'
    
    - name: Create or connect to Workspace
      run: |
        python 'aml_service/00-WorkSpace.py'
    
