name: DevOps for ML (CI/CD)

on:
  push:
    branches:
    - master
    paths:
    - 'code/**'

jobs:
  training:
    name: Model Training
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r 'aml_service/ci_cd/requirements.txt'
    
    - name: Create or Connect to Workspace
      run: |
        python 'aml_service/ci_cd/00-WorkSpace.py' --subscription-id ${{ secrets.SUBSCRIPTION_ID }} --workspace-name ${{ secrets.WORKSPACE_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --location ${{ secrets.LOCATION }} --friendly-name ${{ secrets.FRIENDLY_NAME }}
    
    - name: Create or Load Azure Machine Learning Compute
      run: |
        python 'aml_service/ci_cd/01-AttachAmlCluster.py'
    
    - name: Train Model
      run: |
        python 'aml_service/ci_cd/10-Train.py'
    
    - name: Evaluate and Register Model
      run: |
        python 'aml_service/ci_cd/20-RegisterModel.py'
    
    - name: Profile Model
      run: |
        python 'aml_service/ci_cd/30-ProfileModel.py'
    
    - name: Dev Deployment
      run: |
        python 'aml_service/ci_cd/40-DevDeployment.py'
    
    - name: Test Deployment
      run: |
        python 'aml_service/ci_cd/50-TestDeployment.py'
    
    - name: Production Deployment
      run: |
        python 'aml_service/ci_cd/60-ProdDeployment.py'
